### PR TITLE
BLZG-1461 Add Unit Tests to Blazegraph-samples projects 

### PR DESCRIPTION
**Pull request by krokhaleva**
Added 'sample-tests' project, which contains test suite for all Blazegraph Samples. (BLZG-1461)
Updated pom dependency to 1.5.3. (BLZG-1492)

### CODE REVIEW

**Comment by beebs-systap** [comment]
Computer, please test this.

**Comment by blazegraph** [comment]
Build triggered. sha1 is merged.

**Comment by blazegraph** [comment]
Build started sha1 is merged.

**Comment by blazegraph** [comment]
Build finished. No test results found.

**Comment by beebs-systap** [comment]
Computer, please test this.

**Comment by beebs-systap** [comment]
@krokhaleva We have decided to keep the maven version until 1.6.0.  Please update the POM entries to:
```
<dependency>
   <groupId>com.bigdata</groupId>
   <artifactId>bigdata</artifactId>
   <version>${blazegraph.version}</version>
</dependency>
```

Update the blazegraph.version to 1.5.3-SNAPSHOT.

I'll push the 1.5.3 SNAPSHOT later today.

**Comment by beebs-systap** [comment]
Deployed 1.5.3-SNAPSHOT

**Comment by beebs-systap** [comment]
Computer, please test this.

**Comment by beebs-systap** [comment]
@krokhaleva I resolved the 1.5.3-SNAPSHOT dependency failure.  Please check the samples pom dependencies and add the required jetty dependencies for the tests.

**Comment by beebs-systap** [comment]
PR looks good.  Will merge down and include in the next release of blazegraph-samples.

**Comment by beebs-systap** [comment]
https://jira.blazegraph.com/browse/BLZG-1492

**Pull request merged**
